version: "3.8"
services:
  table-backend:
    image: ${PROJECT_IMAGE}
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --log-config log.yaml --log-level debug --reload
    restart: always
    healthcheck:
      interval: 1m
      timeout: 3s
      retries: 3
      test: curl localhost:8000/ping
    environment:
      - TZ=Asia/Shanghai
      - TABLE_ENV=${TABLE_ENV:-LOCAL}
      - TABLE_LOG_LEVEL=${TABLE_LOG_LEVEL:-INFO}
    networks: 
      - prod_default
    ports:
      - ${PROJECT_PORT:-8001}:8000
networks:
  prod_default:
    external: true
